-- NextAuth.js Supabase Adapter tabloları
-- Bu şema, NextAuth.js'in Supabase ile çalışması için gereklidir.
-- Kaynak: https://next-auth.js.org/adapters/supabase

CREATE TABLE IF NOT EXISTS accounts (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "userId" uuid NOT NULL,
    type text NOT NULL,
    provider text NOT NULL,
    "providerAccountId" text NOT NULL,
    refresh_token text,
    access_token text,
    expires_at bigint,
    token_type text,
    scope text,
    id_token text,
    session_state text,
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT "accounts_userId_fkey" FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "sessionToken" text NOT NULL,
    "userId" uuid NOT NULL,
    expires timestamp with time zone NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT "sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text,
    email text,
    "emailVerified" timestamp with time zone,
    image text,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS verification_tokens (
    identifier text,
    token text,
    expires timestamp with time zone NOT NULL,
    CONSTRAINT verification_tokens_pkey PRIMARY KEY (token)
);

-- Şükür Günlüğü "notes" tablosu
-- user_id, users tablosuna referans veriyor.
CREATE TABLE notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Row Level Security (RLS) Politikaları
-- 1. "notes" tablosu için RLS'i etkinleştir
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- 2. Kullanıcıların kendi notlarını seçebilmesi (görebilmesi) için politika
CREATE POLICY "user_can_select_own_notes"
ON notes FOR SELECT
USING (auth.uid() = user_id);

-- 3. Kullanıcıların kendi notlarını ekleyebilmesi için politika
CREATE POLICY "user_can_insert_own_notes"
ON notes FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4. Kullanıcıların kendi notlarını güncelleyebilmesi için politika
CREATE POLICY "user_can_update_own_notes"
ON notes FOR UPDATE
USING (auth.uid() = user_id);

-- 5. Kullanıcıların kendi notlarını silebilmesi için politika
CREATE POLICY "user_can_delete_own_notes"
ON notes FOR DELETE
USING (auth.uid() = user_id);
